<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title><?php echo $t->_("login") ?></title>
	<link rel="stylesheet" type="text/css" href="/test-php/css/login.css">
</head>
<body>
	<div class="login-container">
		<form action="" method="post">
			<?php if (isset($error) && $error): ?>
				<p class="error-message"><?php echo $t->_('login-incorrect') ?></p>
			<?php endif ?>

			<div class="form-input">
				<?php echo $t->_('username') ?>:
				<input type="text" name="username" value="" placeholder="">
			</div>
			<div class="form-input">
				<?php echo $t->_('password') ?>:
				<input type="password" name="password" value="" placeholder="">
			</div>
			<p class="login-remember"><input type="checkbox" name="remember" id="remember" value=""> <label for="remember"><?php echo $t->_('remember-me') ?></label></p>
			<input type="submit" value="<?php echo $t->_('login') ?>">
	</div>
	<div class="popup">
		<div class="languages">
			<p><span class="lang-bt" value="vi">Tiếng Việt</span> <span class="lang-bt" value="en">English</span></p>
			<i>(Chọn ngôn ngữ)<br>(Choose language)</i>
		</div>
	</div>
	<script src="/test-php/js/jquery-1.11.3.min.js" type="text/javascript"></script>
	<script src="/test-php/js/jquery.cookie.js" type="text/javascript"></script>
	<script src="/test-php/js/login.js" type="text/javascript"></script>
</body>
</html>