<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title><?php echo $t->_('user-page') ?></title>
	<link rel="stylesheet" type="text/css" href="/test-php/css/style.css">
</head>
<body>
<div class="container">
	<header>
		<h2><?php echo $t->_('list-images-page') ?></h2>
	</header>
	<div class="list-images">
		<div class="image-item">
			<div class="image-bg">
				<img src="http://ngecoding.com/images/bank/phalcon-php-egy-uj-perspektiva.png" alt="">
			</div>
			<p>Hình 1 <span>Edit | Delete</span></p>
			<p><i>(Flower.jpg - 123kb)</i></p>
		</div>
		<div class="image-item">
			<div class="image-bg">
				<img src="http://ngecoding.com/images/bank/phalcon-php-egy-uj-perspektiva.png" alt="">
			</div>
			<p>Hình 1 <span>Edit | Delete</span></p>
			<p><i>(Flower.jpg - 123kb)</i></p>
		</div>
		<div class="image-item">
			<div class="image-bg">
				<img src="http://ngecoding.com/images/bank/phalcon-php-egy-uj-perspektiva.png" alt="">
			</div>
			<p>Hình 1 <span>Edit | Delete</span></p>
			<p><i>(Flower.jpg - 123kb)</i></p>
		</div>
		<div class="image-item">
			<div class="image-bg">
				<img src="http://ngecoding.com/images/bank/phalcon-php-egy-uj-perspektiva.png" alt="">
			</div>
			<p>Hình 1 <span>Edit | Delete</span></p>
			<p><i>(Flower.jpg - 123kb)</i></p>
		</div>
		<div class="image-item">
			<div class="image-bg">
				<img src="http://ngecoding.com/images/bank/phalcon-php-egy-uj-perspektiva.png" alt="">
			</div>
			<p>Hình 1 <span>Edit | Delete</span></p>
			<p><i>(Flower.jpg - 123kb)</i></p>
		</div>
		<div class="image-item">
			<div class="image-bg">
				<img src="http://ngecoding.com/images/bank/phalcon-php-egy-uj-perspektiva.png" alt="">
			</div>
			<p>Hình 1 <span>Edit | Delete</span></p>
			<p><i>(Flower.jpg - 123kb)</i></p>
		</div>
		<div class="image-item">
			<div class="image-bg">
				<img src="http://ngecoding.com/images/bank/phalcon-php-egy-uj-perspektiva.png" alt="">
			</div>
			<p>Hình 1 <span>Edit | Delete</span></p>
			<p><i>(Flower.jpg - 123kb)</i></p>
		</div>
		<div class="image-item">
			<div class="image-bg">
				<img src="http://ngecoding.com/images/bank/phalcon-php-egy-uj-perspektiva.png" alt="">
			</div>
			<p>Hình 1 <span>Edit | Delete</span></p>
			<p><i>(Flower.jpg - 123kb)</i></p>
		</div>
		<div class="image-item">
			<div class="image-bg">
				<img src="http://ngecoding.com/images/bank/phalcon-php-egy-uj-perspektiva.png" alt="">
			</div>
			<p>Hình 1 <span>Edit | Delete</span></p>
			<p><i>(Flower.jpg - 123kb)</i></p>
		</div>
		<div class="image-item">
			<div class="image-bg">
				<img src="http://ngecoding.com/images/bank/phalcon-php-egy-uj-perspektiva.png" alt="">
			</div>
			<p>Hình 1 <span>Edit | Delete</span></p>
			<p><i>(Flower.jpg - 123kb)</i></p>
		</div>
	</div>
	<div class="upload-image">
		<button type="button"><?php echo $t->_('upload-image') ?></button>
	</div>
</div>
	<script src="/test-php/js/jquery-1.11.3.min.js" type="text/javascript"></script>
	<script src="/test-php/js/app.js" type="text/javascript"></script>
</body>
</html>